### ISSUE TITLE
 Docker Compose file

### ISSUE THREAD

**Issue by MoRain666** [rolling-scopes/rsschool-scripts#1]
Hello, i try to get data from rsschool-scripts with docker on windows 10 and have some problems like this(screen below)
![image](https://user-images.githubusercontent.com/30127467/43833757-7f9d6afc-9b14-11e8-8723-49a04b8a2bb2.png)

after i check my data base, and i got this:
![image](https://user-images.githubusercontent.com/30127467/43833821-ae27ba6c-9b14-11e8-8eee-77f2382db02f.png)
I am hope for your help!

**Comment by apalchys** [comment]
@MoRain666 could you please try to use my fork?
https://github.com/apalchys/rsschool-scripts

I made some changes in order to understand what's going on.

**Comment by i-runets** [comment]
@apalchys 
![image](https://user-images.githubusercontent.com/35107045/43890585-d6f82a56-9bcf-11e8-9f61-10ff0e309eb7.png)

**Comment by apalchys** [comment]
@i-runets 
Hmm.. could you please do the following using my fork? It seems the docker image was not updated

```
docker-compose rm
docker-compose build
docker-compose up
```

**Comment by i-runets** [comment]
@apalchys I did everything you wrote. 
![image](https://user-images.githubusercontent.com/35107045/43893277-0422479e-9bd7-11e8-9f9f-e6960074bfdd.png)

**Comment by mmetelskiy** [comment]
@MoRain666 @i-runets 
in the root dir: `find . -type f -print0 | xargs -0 dos2unix`
then: `cd development && docker-compose up --build`

**Comment by i-runets** [comment]
@mmetelskiy thx, it worked

**Comment by apalchys** [comment]
Guys, 

Yeah, it seems an issue with line-ending.
I've added a .gitattributes file to my fork. It should unify line-ending across OS and uses LF by default.  It would be great if you can check it on Windows.

Additionally I added .editorconfig.

**Comment by MoRain666** [comment]
@apalchys hi, i cloned your fork and everything works as it should, thanks for the help!

**Comment by apalchys** [comment]
Merged fixes. Please let me know if you see any other issues.
